environement_config:
    max_allowed_power: 100.0
    daily_slot_count: 200

agents:
    utility1:
        type: EFlexAgentPConstant       # trainer type
        p_min: 0.0
        p_max: 20.0
        p_slope: 1

    utility2:
        type: EFlexAgentPConstant       # trainer type
        p_min: 0.0
        p_max: 10.0
        p_slope: 1

    utility3:
        type: EFlexAgentPConstant       # trainer type
        p_min: 0.0
        p_max: 20.0
        p_slope: 1

    utility4:
        type: EFlexAgentPConstant       # trainer type
        p_min: 0.0
        p_max: 10.0
        p_slope: 1

    storage:
        type: EFlexEnergyStorageAgent       # trainer type
        p_min: 0.0
        p_max: 30.0
        p_slope: 1