environement_config:
    max_allowed_power: 100.0
    energy_cost_budget: 10 # 80.0 * .16
    daily_slot_count: 200
    tou_generartor:
        type: STEPTOUGenerator
        steps: [102400, 204800 ]
        values: [ 0.1, 0.1 ]
    load_profile:
        type: STEPLoadProfile
        tolerance_factor: 0.2
        steps: [102400, 204800 ]
        values: [ 100.0, 100.0 ]

agents:
    utility1:
        type: EFlexAgentPConstant       # trainer type
        p_min: 0.0
        p_max: 50.0
        p_slope: 1.0

    utility2:
        type: EFlexAgentPConstant       # trainer type
        p_min: 0.0
        p_max: 15.0
        p_slope: 1.0
#
#    utility3:
#        type: EFlexAgentPConstant       # trainer type
#        p_min: 0.0
#        p_max: 30.0
#        p_slope: 1.0
#
#    utility4:
#        type: EFlexAgentPConstant       # trainer type
#        p_min: 0.0
#        p_max: 30.0
#        p_slope: 1.0
        
#    utility5:
#        type: EFlexAgentPConstant       # trainer type
#        p_min: 0.0
#        p_max: 5.0
#        p_slope: 1.0.0
#
#    utility6:
#        type: EFlexAgentPConstant       # trainer type
#        p_min: 0.0
#        p_max: 5.0
#        p_slope: 1.0
#
#    utility7:
#        type: EFlexAgentPConstant       # trainer type
#        p_min: 0.0
#        p_max: 5.0
#        p_slope: 1.0
#
#    storage:
#        type: EFlexEnergyStorageAgent       # trainer type
#        p_min: 0.0
#        p_max: 20.0
#        p_slope: 1.0
#
#    generator:
#        type: EFLEXEnergyGeneratorAgent       # trainer type
#        p_min: 0.0
#        p_max: 20.0
#        p_slope: 1.0