environement_config:
    max_allowed_power: 100.0

agents:
    Agent_0:
        type: EFlexAgentPConstant       # trainer type
        p_min: 20.0
        p_max: 60.0
        p_slope: 10.0

    Agent_2:
        type: EFlexAgentPConstant       # trainer type
        p_min: 20.0
        p_max: 50.0
        p_slope: 10.0

