environement_config:
    max_allowed_power: 100.0

agents:
    grid:
        type: EFLEXEnergyMainGridAgent       # trainer type
        p_min: 0.0
        p_max: 80.0
        p_slope: 1

    utility1:
        type: EFlexAgentPConstant       # trainer type
        p_min: 0.0
        p_max: 80.0
        p_slope: 1

    utility2:
        type: EFlexAgentPConstant       # trainer type
        p_min: 0.0
        p_max: 80.0
        p_slope: 1

    generator:
        type: EFLEXEnergyGeneratorAgent       # trainer type
        p_min: 0.0
        p_max: 80.0
        p_slope: 1